### ISSUE TITLE
Question about the discriminatorLoss

### ISSUE THREAD

**Issue by xuxu116** [AaronHeee/MEAL#1]
Thanks for shearing your code and it's really a good work
However I am confused by the discriminatorLoss that corresponding to sec 4.3 in your paper. It should be a minimax problem as GAN and the discriminatorLoss only helps to train the discriminator to differentiate teacher\student outputs. I don't find the part of training the student network to 'fool' the discriminator. 
BTW, I think the discriminator can use output_size=1 since there are only two classes.

**Comment by szq0214** [comment]
Hi @xuxu116, thanks for your interests in our work. The similarity loss we used is to force the student network to generate similar outputs as teachers, so that the outputs from students and teachers can 'fool' the discriminators, and the student network and discriminators are trained simultaneously.

**Comment by xuxu116** [comment]
@szq0214 Thanks for your rely!
Yeah the similarity loss is working but I think the discriminators-design shows no contribution to the student network as in the code. Since the discriminatorLoss helps the D-net to differentiate teacher\student and its gradients go through not only D-net but also student-net (the student should learn to produce_ more distinguishable features from the teacher in order to minimized this loss)
Is there any inconsistency between the code and paper? As the D is to maximize _L_-GAN and student to minimize _L_-GAN but I only see the maximize.

**Comment by szq0214** [comment]
@xuxu116, No. Since we adopt discriminators on feature space instead of the image space, so it will not be an ordinary GAN. The similarity loss in our method is used to minimize and discriminators are used to maximize, that's why we call it 'via adversarial learning'. Our purpose and design are to let student network and discriminators train adversarially and simultaneously, so the gradients from discriminators should help student networks when optimizing.

**Comment by xuxu116** [comment]
@szq0214 It is clearly that the similarity and discriminators form an adversarial-pair. 
As described in Sec.4.3 & 4.4, _L_GAN need to be minimized (it is called adversarial loss and I think it is designed to be minimized). However, the discriminatorLoss actually maximize the objective in Eq. 8 rather than minimize the _L_GAN in Eq.10. 

Minimize similarityLoss should minimize adversarial loss implicitly. And I think it is more conventional to train adversarially like:
1. Trained D to maximize Eq.8. (fix student)
2. Trained Student to minimize Eq.10 (fix D)
