### ISSUE TITLE
Cannot get reach to the URL

### ISSUE THREAD

**Issue by chrisyxue** [AaronHeee/MEAL#11]
Sorry, I cannot download the pretrained-model zoo, because I cannot reach the link successfully.
The error goes like :
"onnecting to www.dropbox.com (www.dropbox.com)|2620:100:6032:1::a27d:5201|:443... failed: Network is unreachable.
" 
Why?

**Comment by szq0214** [comment]
Hi @chrisyxue, can you try this URL: https://www.dropbox.com/s/ruh0esxg83z3i3u/checkpoint.zip.

**Comment by xxAna** [comment]
@szq0214 Thank you for your excellent work and the sharing.I face the same download problem and can't download even from https://www.dropbox.com/s/ruh0esxg83z3i3u/checkpoint.zip. Would it be convenient for you to put the pth on the baiduyun disk? It may due to some sensitive problems and we can't successfully download things from google or dropbox from time to time.

**Comment by szq0214** [comment]
Hi @xxAna, thanks for your interests in our work, I have uploaded to baiduyun and can you try this link: https://pan.baidu.com/s/1iefgv6Ms33jfYcsB31Ok4A & password: ri1u

**Comment by xxAna** [comment]
@szq0214 OK, it works! Thank you very much! Best wishes.
